#!/bin/bash

/app/venv/YOUR_PROJECT_NAME/bin/pip install -r requirements-dev.txt

DB_SERVER_OK=0
echo -n "INFO: Testing DB Server"
for i in 1 2 3 4 5 6 7 8 9 0; do
    echo -n "."
    PYTHONPATH=. DJANGO_SETTINGS_MODULE=badgepunch_web.settings /app/venv/YOUR_PROJECT_NAME/bin/python devops/scripts/test_db_conn.py > /dev/null 2>&1
    if [ $? == 0 ]; then
        DB_SERVER_OK=1
		echo OK
        break
    fi
    sleep 1
done
echo

if [ ${DB_SERVER_OK} != 1 ]; then
    echo "ERROR: Can't connect to DB server"
    exit 1
fi

/app/venv/YOUR_PROJECT_NAME/bin/python ./manage.py runserver 0.0.0.0:8000
