version: '2'
services:
    webserver:
        image: YOUR_PATH_TO_YOUR_ECR_REPO.amazonaws.com/YOUR_PROJECT_NAME-webserver:${BUILD_NO}
        mem_limit: 50M
        restart: always
        ports:
            - "80:80"
            - "443:443"
        links:
            - appserver

    appserver:
        image: YOUR_PATH_TO_YOUR_ECR_REPO.amazonaws.com/YOUR_PROJECT_NAME-appserver:${BUILD_NO}
        mem_limit: 200M
        restart: always
        ports:
            - "8000:8000"
        env_file:
            - appserver-ec2.env
        command: --bind 0.0.0.0:8000 --workers 2 --max-requests 1 --error-logfile - --access-logfile - --timeout 60

