#!/bin/bash

set -e

export BUILD_NO=`date -u "+%Y%m%d%H%M"`

PYTHONPATH=${1}
[ -z "${PYTHONPATH}" ] && echo WARNING: Please specify PYTHONPATH param to run manage.py;

# collect static files
( cd ../..; ${PYTHONPATH} ./manage.py collectstatic --noinput; )

# generate git commit file in the context
git rev-parse HEAD > ../../.gitcommit

# we do this to maximise caching,
# and keep dependencies in requirements.txt
python ./gen-dockerfiles-from-template.py

docker-compose build

echo ${BUILD_NO} > .build_no
echo BUILD_NO=${BUILD_NO}
